### ISSUE TITLE
Recursive messages

### ISSUE THREAD

**Issue by letalvoj** [fomkin/zhukov#7]
I really like the codebase and would _love_ to use it to implement interop with libpguery, which [has a protobuf API](https://github.com/pganalyze/libpg_query/blob/13-latest/protobuf/pg_query.proto). ScalaPB is a no-go for several reasons.

I realized that there is a minor limitation blocking me. Adding an extra case 

```scala
  case class E(foo: Foo) extends Foo
```

to https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/test/scala/AdtTest.scala#L9-L13 

breaks the derivation. I thought that wrapping the implicit summons like the following one https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/main/scala/zhukov/derivation/ZhukovDerivationMacro.scala#L172

in `shapeless.Lazy` would solve that issue, yet that is definitely not enough.

@fomkin have you please thought how to overcome that limitation?

**Comment by fomkin** [comment]
Hi, 

The case you described should work with semiauto derivation. https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/test/scala/CompareWithScalapbTest.scala#L63

Maybe you forget to [add sizeMeter ](https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/test/scala/AdtTest.scala#L33) and other instance for `E`? What kind of error you got?

Anyway I'm not sure that this project will have support in the future.
1. Currently I don't have Scala-first projects with PB.
2. Scala 3 has new macros system, so this code should be completely rewritten. I already have experience with two version of macros, and this is not easy, even on development stage.

P.S.
Auto derivation has this problem and didn't find a way to solve it.  https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/test/scala/CompareWithScalapbAutoderivationTest.scala#L27

**Comment by letalvoj** [comment]
> The case you described should work with semiauto derivation.
> Maybe you forget to [add sizeMeter ](https://github.com/fomkin/zhukov/blob/94399cc4290976920d4b9cb693317ea842d03fa8/derivation/src/test/scala/AdtTest.scala#L33) and other instance for `E`? What kind of error you got?

Oh, I might have missed that, I'll check again. Thx.

> Anyway I'm not sure that this project will have support in the future.
> 
> 1. Currently I don't have Scala-first projects with PB.

Well, the lib we are working on is a part of a thesis of my student. Mostly an academic project. Do not worry about us opening bugs or something. It is actually the other way around. _If_ we succeed in adapting this codebase for our use case, would you mind us re-releasing this as a module within the other project? With all the proper acknowledgements and preserved line ownership. Should be within the apache license.

> 2. Scala 3 has new macros system, so this code should be completely rewritten. I already have experience with two version of macros, and this is not easy, even on development stage.

Yeah, that could be a big step. Yet we do not mind since our project is written in Scala 2.13 and do not expect rewriting it in the foreseeable future.

**Comment by fomkin** [comment]
> Well, the lib we are working on is a part of a thesis of my student. Mostly an academic project. Do not worry about us opening bugs or something. It is actually the other way around. If we succeed in adapting this codebase for our use case, would you mind us re-releasing this as a module within the other project? With all the proper acknowledgements and preserved line ownership. Should be within the apache license.

I will glad to see contributors or even new project maintainers :)

**Comment by letalvoj** [comment]
> I will glad to see contributors or even new project maintainers :)

Cool, thx 👍

We mostly need to add annotations, to make sure that there is a bijection between the mimicked `.proto` file and the equivalent ADT and `Enumerations`.

I will keep you updated.
